parameters:
    plugins.content.repository.class: Cmf\ContentBundle\Repository\Repository
    plugins.event_subscriber.bundle.class: Cmf\ContentBundle\EventSubscriber\EventSubscriberBundle

services:
    plugins_content.repository:
        class: %plugins.content.repository.class%
        arguments: ['@doctrine.orm.entity_manager']

    #
    # configuration of the event subscriber of entities
    #
    plugins.event_subscriber.bundle:
        class: %plugins.event_subscriber.bundle.class%
        arguments: [@service_container]
        tags:
            - { name: doctrine.event_subscriber }        